supported_models:
  - openai
date_formats:
  arxiv:
    metadata: "%a, %d %b %Y %H:%M:%S %Z"
paths:
  agents: XivMind/configs/agents
  arxiv:
    metadata: XivMind/data/arxiv
    summaries: XivMind/data/arxiv/summaries
  embeddings:
    openai: XivMind/data/embeddings/openai
  faiss:
    openai: XivMind/data/faiss/openai
files:
  arxiv:
    metadata: arxiv-metadata-oai-snapshot.json
    index: arxiv-metadata-index.pkl
    summaries: arxiv-summaries.json
  embeddings:
    openai: openai-embeddings.pkl
  faiss:
    openai: openai-faiss.index
fields:
  metadata:
    - id
    - submitter
    - authors
    - title
    - comments
    - journal-ref
    - doi
    - report-no
    - categories
    - license
    - abstract
    - versions
    - update_date
    - authors_parsed