supported_models:
  - openai
API:
  default:
    rate_limit_tokens_per_minute: 100000
    rate_limit_requests_per_minute: 250
    rate_limit_requests_per_day: 5000
  openai:
    gpt-3.5-turbo:
      max_concurrent_requests: 20
      rate_limit_tokens_per_minute: 200000
      rate_limit_requests_per_minute: 500
      rate_limit_requests_per_day: 10000

date_formats:
  arxiv:
    metadata: "%a, %d %b %Y %H:%M:%S %Z"
paths:
  agents: XivMind/configs/agents
  arxiv:
    metadata: XivMind/data/arxiv
    summaries: XivMind/data/arxiv/summaries
  embeddings:
    openai: XivMind/data/embeddings/openai
  faiss:
    openai: XivMind/data/faiss/openai
files:
  arxiv:
    metadata: arxiv-metadata-oai-snapshot.json
    index: arxiv-metadata-index.pkl
    summaries: arxiv-summaries.db
    embeddings: arxiv-summaries.db
  faiss:
    openai: openai-faiss.index
sql:
  main-path: XivMind/configs/sql_queries
  create-summaries-table: create-summaries-table.sql
  insert-summary: insert-summary.sql
  select-summaries-by-primary-key: select-summaries-by-primary-key.sql
  select-all-summaries: select-all-summaries.sql
  select-summaries-by-full-model: select-summaries-by-full-model.sql
  select-summaries-by-summarizer: select-summaries-by-summarizer.sql
  select-summaries-by-arxiv-id: select-summaries-by-arxiv-id.sql
  select-summaries-by-full-model-and-arxiv-id: select-summaries-by-full-model-and-arxiv-id.sql
  select-summaries-by-summarizer-and-full-model: select-summaries-by-summarizer-and-full-model.sql
  select-summaries-by-summarizer-and-arxiv-id: select-summaries-by-summarizer-and-arxiv-id.sql
  select-summaries-by-summarizer-and-full-model-and-arxiv-id: select-summaries-by-summarizer-and-full-model-and-arxiv-id.sql
arxiv:
fields:
  metadata:
    - id
    - submitter
    - authors
    - title
    - comments
    - journal-ref
    - doi
    - report-no
    - categories
    - license
    - abstract
    - versions
    - update_date
    - authors_parsed